# Tutorial 5 Functions and NumPy

## Aim

In this tutorial, you will learn how to define custom function and an important library Numpy.

## Prerequisites

Python3

### Functions
A function is a block of code which only runs when it is called.

In [1]:
def mtrn4110():      # define a function called mtrn4110 which print a sentence
    print("mtrn4110 is the best!")   

mtrn4110()   # call the function

mtrn4110 is the best!


In [2]:
def find_maximum_number_index(list):   # define a function which returns maximum number in the list
    for index, item in enumerate(list):
        if index == 0:
            maximum = item
        elif item > maximum:
            maximum = item
    
    return maximum

list_1 = [5, 2, 1, 8, 3, 4]
maximum_number = find_maximum_number_index(list_1)
print('maximum number is {}'.format(maximum_number))

maximum number is 8


### NumPy
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [3]:
# import the library
import numpy as np

# Create array
list_2 = np.array([5, 2, 1, 8, 3, 4])  # create a one dimensional array list_2
print(type(list_2))                    # print the type
print(list_2.shape)                    # print the shape of list_2
print(list_2[2])                       # access third item

# Slicing and indexing
print(list_2[2:4:1])              # '2' is starting index, '4' is stopping index, '1' is the step

list_3 = np.array(([1, 2, 3], [3, 4, 5])) # create a two dimensional array list_3
print(list_3[1][2])                       # print '5' 

<class 'numpy.ndarray'>
(6,)
1
[1 8]
5


In [4]:
# Useful functions to create arrays

a = np.zeros((2, 2))   # create a 2 by 2 array of all zeros
print(a)

b = np.ones((3, 1))    # create a 3 by 1 array of all ones
print(b)

[[0. 0.]
 [0. 0.]]
[[1.]
 [1.]
 [1.]]


In [5]:
# Boolean array indexing
bool_idx = (list_2 > 2)  # This will returns a numpy array of booleans of the same shape as list_2
                         # and each element of bool_idx tells you whether each element of list_2 
                         # at the same location is bigger than 2 
print(bool_idx)
print(list_2[bool_idx])  # print all values of list_2 that are bigger than 2

# All of the above in one statement
print(list_2[list_2>2])


[ True False False  True  True  True]
[5 8 3 4]
[5 8 3 4]


In [6]:
# Datatypes
a = np.array([1, 2])
print(a.dtype)

b = np.array([1, 2.0])
print(b.dtype)

c =np.array([1, 2], dtype=np.uint8)   # Force a particular datatype
print(c.dtype)    

int32
float64
uint8


In [7]:
# Array Basic Math

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum
print(x + y)
print(np.add(x, y))

# Elementwise subtraction
print(x - y)
print(np.subtract(x, y))

# Elementwise product
print(x * y)
print(np.multiply(x, y))

# Elementwise division
print(x / y)
print(np.divide(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
# Useful functions for performing advanced computing

m = np.array([[1,5],
              [3,4]])
print(np.sum(m))          # Compute sum of all elements 
print(np.sum(m, axis=0))  # Compute sum of each column  
print(np.sum(m, axis=1))  # Compute sum of each row; prints

print(np.amax(m))           # Find the maximum value of all elements.
print(np.amax(m, axis = 0)) # Maxima along the first axis
print(np.amax(m, axis = 1)) # Maxima along the second axis

print(np.amin(m))           # Find the minimum value of all elements.
print(np.amin(m, axis = 0)) # Minima along the first axis
print(np.amin(m, axis = 1)) # Minima along the second axis

n = np.array([1,2,3,4,5,6,7,8,9])
n = np.reshape(n,(3,3))     # Reshape array n to 3 by 3
print(n)

13
[4 9]
[6 7]
5
[3 5]
[5 4]
1
[1 4]
[1 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
